services:
  postgres:
    image: postgres:16
    container_name: whispr-postgres
    restart: always
    env_file:
      - ../.env.development
    ports:
      - 5433:5432
    volumes:
      - whispr-postgres-data:/var/lib/postgresql/data      
    networks:
      - whispr-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: whispr-pgadmin
    restart: always
    env_file:
      - ../.env.development
    ports:
      - 5051:80
    depends_on:
      - postgres
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - whispr-network

  seq:
    image: datalust/seq:latest
    container_name: whispr-seq
    env_file:
      - ../.env.development
    ports:
      - "5341:80"
    volumes:
      - whispr-seq-data:/data
    restart: unless-stopped

volumes:
  whispr-postgres-data:
  whispr-seq-data:

networks:
  whispr-network:
    driver: bridge