FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY teste.csproj .
RUN dotnet restore teste.csproj

COPY . .
RUN dotnet build teste.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish teste.csproj -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY nginx.conf /etc/nginx/nginx.conf